[tool.poetry]
name = "onestack"
version = "0.1.0"
description = "The one Data Stack to rule them all. Deploy all you need for your data project, in open source fashion ğŸš€ğŸŒ"
authors = ["Alfredo Suarez <31414624+alfredosa@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
dbt-postgres = "^1.5.1"
pandas = "^2.0.2"
jupyter = "^1.0.0"
prettytable = "^3.8.0"
dbt-core = "^1.5.1"
dbt-spark = {extras = ["pyhive"], version = "^1.5.0"}
dbt-trino = "^1.5.0"
pyspark = "^3.4.0"
dagit = "^1.3.10"
dagster = "^1.3.10"
dagster-gcp = "^0.19.10"
dagster-dbt = "^0.19.10"
dagster-pyspark = "^0.19.10"
dagster-spark = "^0.19.10"
dagster-meltano = "^1.3.0"
awscliv2 = "^2.2.0"
markupsafe = "^2.1.3"
trino = "^0.326.0"
requests = "^2.31.0"
kaggle = "^1.5.13"
yfinance = "^0.2.20"
pmdarima = "^2.0.3"
matplotlib = "^3.7.1"
black = "^23.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
